import { Media, MediaType } from "@/types/media";
import { Post, PostType, PostVisibility } from "@/types/post";
import { MinimalUser } from "@/types/user";

export const dummyMedia: Media[] = [
  {
    id: "1",
    url: "https://example.com/image1.jpg",
    type: MediaType.IMAGE,
    createdAt: new Date().toISOString(),
    thumbnailUrl: null,
  },
  {
    id: "2",
    url: "https://example.com/image3.png",
    type: MediaType.IMAGE,
    createdAt: new Date().toISOString(),
    thumbnailUrl: null,
  },
  {
    id: "3",
    url: "https://example.com/video1.mp4",
    type: MediaType.VIDEO,
    createdAt: new Date().toISOString(),
    thumbnailUrl: "https://example.com/video1-thumbnail.jpg",
  },
  {
    id: "4",
    url: "https://example.com/image2.png",
    type: MediaType.IMAGE,
    createdAt: new Date().toISOString(),
    thumbnailUrl: null,
  },
];

export const dummyMinimalUsers: MinimalUser[] = [
  {
    id: "1",
    email: "user1@example.com",
    username: "user1",
    avatar: null,
  },
  {
    id: "2",
    email: "user2@example.com",
    username: "user2",
    avatar: null,
  },
  {
    id: "3",
    email: "user3@example.com",
    username: "user3",
    avatar: null,
  },
];

export const dummyPosts: Post[] = [
  {
    id: "1",
    content: "This is a dummy post 1",
    mentions: [],
    tags: ["fun", "test"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[0],
    stats: {
      postId: "1",
      likesCount: 5,
      commentsCount: 0,
      repostsCount: 0,
      viewsCount: 40,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [dummyMedia[0]],
  },
  {
    id: "2",
    content: "Loving this view from the mountains 🏔️",
    mentions: ["user2"],
    tags: ["travel", "nature"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[1],
    stats: {
      postId: "2",
      likesCount: 22,
      commentsCount: 3,
      repostsCount: 2,
      viewsCount: 180,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [dummyMedia[1]],
  },
  {
    id: "3",
    content: "Quick coding session before bed 😴💻",
    mentions: [],
    tags: ["coding", "lateNight"],
    visibility: PostVisibility.FOLLOWERS,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[2],
    stats: {
      postId: "3",
      likesCount: 12,
      commentsCount: 4,
      repostsCount: 0,
      viewsCount: 110,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [],
  },
  {
    id: "4",
    content: "Watch this quick travel vlog! 🌍🎥",
    mentions: [],
    tags: ["vlog", "adventure"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[0],
    stats: {
      postId: "4",
      likesCount: 48,
      commentsCount: 6,
      repostsCount: 3,
      viewsCount: 520,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [dummyMedia[2]],
  },
  {
    id: "5",
    content: "Reposting this awesome view from @user2!",
    mentions: ["user2"],
    tags: ["repost", "landscape"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.REPOST,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: "2",
    parentId: null,
    repostId: "2",
    author: dummyMinimalUsers[0],
    stats: {
      postId: "5",
      likesCount: 8,
      commentsCount: 1,
      repostsCount: 1,
      viewsCount: 70,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [],
  },
  {
    id: "6",
    content: "Totally agree with this post 👏",
    mentions: [],
    tags: ["agree", "discussion"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.COMMENT,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: "1",
    wasRepostFor: null,
    parentId: "1",
    repostId: null,
    author: dummyMinimalUsers[1],
    stats: {
      postId: "6",
      likesCount: 3,
      commentsCount: 0,
      repostsCount: 0,
      viewsCount: 40,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [],
  },
  {
    id: "7",
    content: "Throwback to my old project launch day 🚀",
    mentions: [],
    tags: ["throwback", "startup"],
    visibility: PostVisibility.FOLLOWERS,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[2],
    stats: {
      postId: "7",
      likesCount: 30,
      commentsCount: 5,
      repostsCount: 2,
      viewsCount: 290,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [dummyMedia[3]],
  },
  {
    id: "8",
    content: "This quote really hit me today — 'Code. Sleep. Repeat.' 💭",
    mentions: [],
    tags: ["quote", "devlife"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.QUOTE,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: "3",
    parentId: null,
    repostId: "3",
    author: dummyMinimalUsers[1],
    stats: {
      postId: "8",
      likesCount: 14,
      commentsCount: 2,
      repostsCount: 1,
      viewsCount: 130,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [],
  },
  {
    id: "9",
    content: "Private thoughts stay private 🧠",
    mentions: [],
    tags: ["private", "journal"],
    visibility: PostVisibility.PRIVATE,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[0],
    stats: {
      postId: "9",
      likesCount: 0,
      commentsCount: 0,
      repostsCount: 0,
      viewsCount: 1,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [],
  },
  {
    id: "10",
    content: "Big thanks to @user1 for helping me debug this issue! 🐛❤️",
    mentions: ["user1"],
    tags: ["thanks", "teamwork"],
    visibility: PostVisibility.PUBLIC,
    postType: PostType.ORIGINAL,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    wasCommentFor: null,
    wasRepostFor: null,
    parentId: null,
    repostId: null,
    author: dummyMinimalUsers[2],
    stats: {
      postId: "10",
      likesCount: 17,
      commentsCount: 4,
      repostsCount: 0,
      viewsCount: 210,
      lastStatsUpdate: new Date().toISOString(),
    },
    media: [],
  },
];
